AWSTemplateFormatVersion: '2010-09-09'
Description: Playground of creating an instance.

Parameters:
  Project:
    Default: playground
    Description: Name of the Project
    Type: String

  ImageId:
    Default: ami-0c5199d385b432989
    Description: AWS server instance id.
    Type: String

  KeyName:
    Description: SSH key name.
    Type: String

  VPCID:
    Description: VPC ID.
    Type: String

  PublicSubnet:
    Description: Public subnet id.
    Type: String


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Namespace"
        Parameters:
          - Project
      -
        Label:
          default: "Tech spec"
        Parameters:
          - ImageId
          - KeyName

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.medium"
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref SecurityGroup
          SubnetId: !Ref PublicSubnet
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash -ex
            apt update
            apt install -y python3-dev python3-pip
            pip3 install -U virtualenv  # system-wide install

            python3 --version
            pip3 --version
            virtualenv --version

            virtualenv --system-site-packages -p python3 ./venv
            source ./venv/bin/activate  # sh, bash, ksh, or zsh

            pip3 install --upgrade pip

            pip3 install --upgrade tensorflow

            python -c "import tensorflow as tf; print(tf.__version__)"

            pip3 install --upgrade jupyter

      Tags:
        -
          Key: Name
          Value: !Sub ${Project}-kx

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${Project}-kx-sg
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub ${Project}-kx-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          FromPort: '22'
          ToPort: '22'
        - IpProtocol: tcp
          CidrIp: "0.0.0.0/0"
          FromPort: '8000'
          ToPort: '8000'
